on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  monitor-upstream-release:
    permissions:
      issues: write
    uses: canonical/robotics-actions-workflows/.github/workflows/upstream-gh-tag-monitor.yaml@main
    with:
      source-repo: "atuinsh/atuin"
